### ISSUE TITLE
Getting Exception while running in development mode

### ISSUE THREAD

**Issue by guruprasaad123** [allenRoyston/vue-es6-webpack#1]
I cloned this repo and installed all the dependencies using the command<br>
```
npm install
```
![capture](https://user-images.githubusercontent.com/19173193/36804224-ecab74b2-1cdf-11e8-9a9b-16bd85e091ea.PNG)
All the packages are installed correctly as you can see from the screenshot above.while running in development mode using the command.<br>
```
npm run dev
```
Am getting these exceptions below while executing these commands.<br>
```
$ npm run dev

> testvue@1.0.0 dev D:\workspace\@hack_earth\vue-es6\vue-es6-webpack
> node build/dev-server.js

module.js:538
    throw err;
    ^

Error: Cannot find module './templates.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\workspace\@hack_earth\vue-es6\vue-es6-webpack\node_modules\chalk\index.js:6:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testvue@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the testvue@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Guru\AppData\Roaming\npm-cache\_logs\2018-02-28T17_55_11_204Z-debug.log
```
Hope to resolve this sooner.Thank you.

**Comment by allenJynRoyston** [comment]
Hi, I'll check this out and get back to you soon.

**Comment by allenJynRoyston** [comment]
In the meantime, maybe this repo can work for whatever you need it for.  It works more or less the same way:

https://github.com/allenRoyston/vue-es6-webpack-express-clean

**Comment by guruprasaad123** [comment]
that's Great @allenRoyston and thanks for the repo!
